### ISSUE TITLE
關於韻母iu和aoh個問題

### ISSUE THREAD

**Issue by laubonghaudoi** [edward-martyr/rime-yahwe_zaonhe#2]
根據[吳語協會](http://wu-chinese.com/romanization/shanghai.html)中個方案，「女」字個拼音是nyiu，韻母裏向弗有yu。但是碼表中只能打nyu才能出「女」字，nyu是弗是nyiu個簡寫？如果是，那應該允許打nyiu也能出「女」。

同樣地，「與」只能打yu，弗能打iu，而「於」則打iu、yu均可，iu和yu有啥區別？

---

另外，吳語協會方案裏廂嘸沒aoh箇個韻母，但是「格」、「隔」等字儕拼kaoh，是啥原因呢？

**Comment by shinzoqchiuq** [comment]
吳語協會個方案裏，聲母 ny 個拼法如同普通話個 y，單獨拼 i、in、ih 個辰光弗簡寫，其他情況要簡寫。譬如：泥 nyi，娘 nyan。

iu 清，yu 濁，yu 相當於 gh+iu。碼表裏「於」有兩種讀法，所以均可。

---

吳語協會個方案裏 aeh、ah、aoh、oh 分別表示老派上海話裏個 [aʔ]、[ɑʔ]、[ɔʔ]、[oʔ]。中派上海話裏，[aʔ]、[ɑʔ] 合併，[ɔʔ]、[oʔ] 合併，故只有 ah、oh。法吳個音系裏 [aʔ]、[ɑʔ] 未合併，[ɔʔ]、[oʔ] 合併，分別用 aq、aoq、oq 表示 [aʔ]、[ɑʔ]、[oʔ]。此地個 aoh 是 @edward-martyr 轉換錯誤，法吳個 aq 當轉爲 aeh，aoq 當轉爲 ah。另外，中派上海話是弗分 aeh、ah 個。

具體講起來，法吳拼音值。所以入聲個 aq[aʔ]、aoq[ɑʔ]、oq[oʔ] 分別對應陽聲個 an[ã]、aon[ɑ̃]、on[oŋ]。但是根據音韻地位，[aʔ] 來自中古咸山攝入聲，應該與咸山攝陽聲（aen > ae > e [ɛ̃ > ɛ > ᴇ]）搭配，所以協會式吳拼裏拼作 aeh。

**Comment by laubonghaudoi** [comment]
既然是介樣子，碼表應該允許打 ghiu = yu、ghieu = yeu、ghia = ya 等等，另外吳語協會官網浪向也應該說明清楚。

---

關於aoh、ah個問題，我猜應該是@edward-martyr 在做箇個碼表個辰光直接用法吳個碼表轉換過來，所以勒海法吳裏向個對立還嘸沒手動合併整理好？

**Comment by yuanhao-chen-nyoeghau** [comment]
@laubonghaudoi @shinzoqchiuq  關於 ah aeh（現在版本 aoh ah）個事體我會得儘快改脫（實際上因爲我自家用個辰光儕是直接儕打ah所以沒注意過）。

關於 _nyi(u, etc.)_ （現在版本 ny(u)）搭 _ghi(u, etc.)_（現在版本 y(u)），箇算是吳語協會個拼音標準，應該以現版本爲正。因爲箇個雖然講是增加靈活性（類似於普通話拼音正字法裏向嘸沒 jü，但是 jv 也可以打出 ju 來，雖然實際箇 u 是按 ü 發音個。箇就是拼音設計爲仔拼寫方便），但是勒該吳語拼音裏增加了簡寫個負擔。譬方，本生用yau打「搖」，用ghiau打「也要」之類應該是最優方案；而弗必要 ghiau打「搖」，ghaiau打「也要」。

另外，yu（等於 ghiu）、iu 因爲是清濁音個區別（國際音標分別 /ɦy/, /y/），所以弗能混同。

謝謝兩位個提議！

**Comment by laubonghaudoi** [comment]
@edward-martyr 所以，應該說是吳語協會官網上向寫漏了 ghi 簡寫爲 y 箇條規則？謝謝兩位個解答。

**Comment by yuanhao-chen-nyoeghau** [comment]
@laubonghaudoi 是個。箇應該作爲拼寫規則個一部分。

**Comment by yuanhao-chen-nyoeghau** [comment]
Addressed in #3. Closing this issue.
