### ISSUE TITLE
能否考慮向 iRime-Resource 加入本方案

### ISSUE THREAD

**Issue by laubonghaudoi** [edward-martyr/rime-yahwe_zaonhe#4]
目前 iRime 默認個吳語拼音方案是法吳，希望能夠 PR 箇個協會方案進去雲方案箇搭 https://github.com/jimmy54/iRime-Resource 箇樣子用戶就能一鍵下載協會拼音，交關方便。

**Comment by yuanhao-chen-nyoeghau** [comment]
謝謝儂個建議，我已經提交哉。https://github.com/jimmy54/iRime-Resource/pull/26

**Comment by laubonghaudoi** [comment]
謝謝儂！另外有一個建議，就是現在兩個方案儕是叫「吳協式上海言話」分弗清阿里一個是舊版，最好加上「舊版」兩字到方案名裏向

**Comment by yuanhao-chen-nyoeghau** [comment]
嗯確實有箇種問題，我已經垃該 https://github.com/edward-martyr/rime-yahwe_zaonhe/commit/a3aef01743bd8b43c72749c3504165a823d5e242 修改脫了。

「阿里」可以寫作何裏，gha li。

**Comment by laubonghaudoi** [comment]
好個，我以後就寫何裏😁
